server.port=8081


#spring.datasource.url=jdbc:mysql://mysql:3306/laptopshop
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

logging.level.org.springframework.web=DEBUG

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

server.servlet.session.timeout=30m

spring.elasticsearch.uris=http://elasticsearch:9200
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

logging.level.org.springframework.session=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG

#SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/laptopshop

#SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/laptopshop